services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    env_file: 
      - .env
    depends_on:
      - mysql
    volumes:
      - /var/www/html
      - ./bdm-digital-website-api-theme:/var/www/html/wp-content/themes/bdm-digital-website-api-theme
      - ./classic-editor:/var/www/html/wp-content/plugins/classic-editor
      - ./WP-SCSS-master:/var/www/html/wp-content/plugins/WP-SCSS-master
      - ./wp-openapi:/var/www/html/wp-content/plugins/wp-openapi
      - ./sass-to-css-compiler:/var/www/html/wp-content/plugins/sass-to-css-compiler
      - ./acf-to-rest-api:/var/www/html/wp-content/plugins/acf-to-rest-api
      - ./advanced-custom-fields-pro:/var/www/html/wp-content/plugins/advanced-custom-fields-pro
      - ./wp-rest-api-controller:/var/www/html/wp-content/plugins/wp-rest-api-controller
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-content:/var/www/html/wp-content    
      - ./docs:/var/www/html/docs   
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
volumes:
  db_data: