services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      REDIS_HOST: redis
    env_file: 
      - .env
    depends_on:
      - mysql
      - redis
    volumes:
      - /var/www/html
      - ./wp-content:/var/www/html/wp-content    
      - ./bdm-digital-website-api-theme:/var/www/html/wp-content/themes/bdm-digital-website-api-theme
      - ./classic-editor:/var/www/html/wp-content/plugins/classic-editor
      - ./wp-rest-cache:/var/www/html/wp-content/plugins/wp-rest-cache
      - ./quick-featured-images:/var/www/html/wp-content/plugins/quick-featured-images
      - ./wp-openapi:/var/www/html/wp-content/plugins/wp-openapi
      - ./acf-to-rest-api:/var/www/html/wp-content/plugins/acf-to-rest-api
      - ./advanced-custom-fields-pro:/var/www/html/wp-content/plugins/advanced-custom-fields-pro
      - ./wp-rest-api-controller:/var/www/html/wp-content/plugins/wp-rest-api-controller
      - ./bdm-firebase-bff:/var/www/html/wp-content/plugins/bdm-firebase-bff
      - ./jwt-authentication-for-wp-rest-api:/var/www/html/wp-content/plugins/jwt-authentication-for-wp-rest-api
      - ./all-in-one-wp-migration-unlimited-main:/var/www/html/wp-content/plugins/all-in-one-wp-migration-unlimited-main
      - ./redis-cache:/var/www/html/wp-content/plugins/redis-cache
      - ./polylang-pro:/var/www/html/wp-content/plugins/polylang-pro
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docs:/var/www/html/docs   
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql 

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
volumes:
  db_data:
  redis_data: