service: dashboar-file-processor-lambda
frameworkVersion: '^3.0.0'

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-localstack
  - serverless-offline-sqs
  # - serverless-offline-s3 
  - serverless-offline

configValidationMode: warn

package:
  individually: true

custom:
  serverless-offline-sqs:
    apiVersion: '2012-11-05'
    endpoint: 'http://127.0.0.1:4566'
    region: us-east-2
    accessKeyId: 'root'
    secretAccessKey: 'root'
  

  # serverless-offline-s3:
  #   autoCreate: true
  #   endpoint: 'https://s3.us-east-2.amazonaws.com'
  #   region: us-east-2
  #   accessKeyId: '${env:AWS_ACCESS_KEY_ID}'
  #   secretAccessKey: ${env:AWS_SECRET_ACCESS_KEY} 
  #   buckets:
  #     - name: development-dashboard-documents
  

  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

  serverless-offline:
    httpPort: 6870
    lambdaPort: 3003
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListBucket
          Resource:
            - "arn:aws:s3:::development-dashboard-documents"
            - "arn:aws:s3:::development-dashboard-documents/*"

functions:
  dashbooardFileProcessor:
    timeout: 30
    memorySize: 512
    handler: ./src/functions/dashboard-file-processor/handler.handler
    events:
      - http:
          method: get
          path: /dashboard-file-processor
      - s3:
          bucket: development-dashboard-documents
          event: s3:ObjectCreated:*
          existing: true

  transferAssets:
    timeout: 30
    memorySize: 512
    handler: ./src/functions/dashboard-transfer-assets/handler.handler
    events:
      - http:
          method: post
          path: /transfer-assets
      - sqs:
          arn:
            Fn::GetAtt:
              - DashboardTransferProcessingQueue
              - Arn
          batchSize: 1
    environment:
      AWS_COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_CLIENT_ID_SECRET: ${env:AWS_COGNITO_CLIENT_ID_SECRET}
      BLOCKCHAIN_API_URL: ${env:BLOCKCHAIN_API_URL}
      BLOCKCHAIN_API_KEY_HASH: ${env:BLOCKCHAIN_API_KEY_HASH}


resources:
  Resources:
    # Fila SQS para enviar as transações do POS para o escritor
    DashboardTransferProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${file(./src/common/serverless/sqs/index.js):build.DashboardTransferProcessingQueueFifo}
        FifoQueue: true